version: "3.8"
services:
  mysqldb:
    container_name: productdb
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=13377331
      - MYSQL_DATABASE=productdb
    ports:
      - 3306:3306
    networks:
      - my-network
  backend:
    container_name: backend-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    networks:
      - my-network
  frontend:
    container_name: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - my-network
networks:
  my-network: