version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your-root-password
      MYSQL_DATABASE: your-database-name
      MYSQL_USER: your-username
      MYSQL_PASSWORD: your-password
    ports:
      - "3306:3306"
