# Estágio 1: Build do Aplicativo Java
FROM maven:3.8.3-openjdk-11 AS build
WORKDIR /app
COPY backend/ .
RUN mvn clean package -DskipTests

# Estágio 2: Runtime
FROM adoptopenjdk/openjdk11:alpine-jre
WORKDIR /app
COPY --from=build /app/target/your-backend-app.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
