version: "3.8"
services:
  application:
    container_name: app
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME={DB_NAME}
  mysql:
    container_name: productdb
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_USERNAME=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
