# Estágio 1: Build do Aplicativo React
FROM node:14 AS build
WORKDIR /app
COPY frontend/ .
RUN npm install
RUN npm run build

# Estágio 2: Servir o Aplicativo React
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
